image:
  repository: galaxy/galaxy-min
  tag: 21.01
  pullPolicy: IfNotPresent

webHandlers:
  replicaCount: 1

jobHandlers:
  replicaCount: 1

resources:
  requests:
    cpu: 0.3
    memory: 1G
  limits:
    cpu: 1
    memory: 2G

persistence:
  storageClass: standard

influxdb:
  enabled: false

postgresql:
  persistence:
    storageClass: standard
