apiVersion: v1
kind: ReplicationController
metadata:
        name: postgresql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: postgresql-server
    spec:
      containers:
      - name: postgresql-server
        image: postgres{{.Values.postgres_image_tag}}
        env:
          - name: "PGDATA"
            value: {{.Values.postgres_mount_point_PGDATA}}/{{.Values.postgres_PGDATA}}
          - name: "POSTGRES_DB"
            valueFrom:
              configMapKeyRef:
                      name: db-connection
                      key: db.name
          - name: "POSTGRES_USER"
            valueFrom:
              configMapKeyRef:
                      name: db-connection
                      key: db.user
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                      name: galaxy-postgres-secret
                      key: password 
        ports:
          - containerPort: 5432
{{ if .Values.postgres_pvc }}
        volumeMounts:
          - mountPath: {{.Values.postgres_mount_point_PGDATA}}
            name: postgres-pvc
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
              claimName: {{.Values.postgres_pvc}}
{{ end }}
